version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    build: simple_solutions
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    build: infra
    ports:
      - "8081:8081"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data2: